/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

//import com.sun.istack.internal.logging.Logger;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JTextField;
import java.sql.*;
import java.math.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Ricardo
 */
public class Banquetes extends javax.swing.JFrame {
    /*Variables para preparar los queries*/
    PreparedStatement ps;
    ResultSet rs;
    ArrayList<detalles_pedido> lista = new ArrayList<detalles_pedido>();
    
    int mouseX,mouseY;
    public Banquetes() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Nuevo pedido");
        transparencia();
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("ImagenesSistema/IMA03.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesSistema/minimize.png"))); // NOI18N
        jButton3.setToolTipText("Minimizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 30, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesSistema/exit.png"))); // NOI18N
        jButton4.setToolTipText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 30, 30));

        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel12MouseDragged(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 40));

        jLabel1.setText("Nombre de cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 122, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 118, 490, -1));

        jLabel2.setText("Domicilio: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 164, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 160, 532, -1));

        jLabel3.setText("Tel. Casa:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 211, -1, -1));

        jLabel4.setText("Tel. Oficina: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 258, -1, -1));

        jLabel5.setText("Fecha del evento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 202, -1, 34));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 207, 172, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 254, 172, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setText("NUEVO PEDIDO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 207, 233, -1));

        jButton1.setText("Realizar nota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 573, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 573, 92, -1));

        jLabel8.setText("Detalles del pedido:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 320, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 320, 492, 130));

        jLabel7.setText("Subtotal: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 480, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 476, 184, -1));

        jLabel9.setText("Depósito por posibles faltantes o rupturas:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 522, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 518, 184, -1));

        jLabel11.setText("Correo electrónico:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 258, 112, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 254, 233, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesSistema/fondoClochard.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void transparencia(){
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Realizar nuevo pedido
        /*Día en curso*/
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingrese un nombre de cliente");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        if(jTextField2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingrese un domicilio");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        if(jTextField3.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un número telefónico");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }else if(jTextField3.getText().length() > 10 ){
            JOptionPane.showMessageDialog(null, "Ingrese un número telefónico válido");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        if(jTextField4.getText().length() > 10 ){
            JOptionPane.showMessageDialog(null, "Ingrese un número telefónico válido");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        Pattern pattern = Pattern.compile("^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@" + "[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,4})$");
        Matcher matcher = pattern.matcher(jTextField8.getText().toLowerCase());
        if(!matcher.matches()){
            JOptionPane.showMessageDialog(null, "Ingrese una dirección de correo válida");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        if(jTextArea1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese detalles del pedido");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        if(jTextField5.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad de subtotal");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        if(jTextField6.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad del depósito");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            return;
        }
        LocalDate ld = LocalDate.now();
        String fecha_hoy = ld.getYear() + "-"+ld.getMonthValue()+"-"+ld.getDayOfMonth();
        System.out.println(fecha_hoy + "\n" + ld.getDayOfMonth());
        Connection con = null;
        double subTotal, deposito,total;
        subTotal = Double.parseDouble(jTextField5.getText());
        deposito = Double.parseDouble(jTextField6.getText());
        total = subTotal + deposito;
        NuevoPedido np;
        np = new NuevoPedido(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText(),0,null,jTextArea1.getText(),subTotal,deposito,total,jTextField8.getText());
        boolean parse = true;
        try{
            Long.parseLong(np.getNumCasa());
        }catch(Exception e){
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            parse = false;
            JOptionPane.showMessageDialog(null, "Ingrese un número telefonico valido");
            return;
        }
        try{
            int choice = JOptionPane.showConfirmDialog(null, "¿Estás seguro de realizar el pedido con los datos ingresados?","\nRealizar pedido",JOptionPane.YES_NO_OPTION);
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if(choice == 1){
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                return;
            }
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            con = getConection();
            ps = con.prepareStatement("insert into cliente (cliente,domicilio,num_casa,num_oficina,fecha_evento,fecha_pedido,detalles_pedido,subtotal,deposito,total,correoE) values(?,?,?,?,?,?,?,?,?,?,?);");
            ps.setString(1, np.getCliente());
            ps.setString(2, np.getDomicilio());
            ps.setString(3,np.getNumCasa());
            ps.setString(4, np.getNumOficina());
            ps.setString(5, np.getFecha_evento());
            ps.setString(6, fecha_hoy);
            ps.setString(7, np.get_detallePedido());
            ps.setDouble(8, np.get_subtotal());
            ps.setDouble(9, np.get_deposito());
            ps.setDouble(10, np.get_total());
            ps.setString(11, np.getCorreo());
            int exe = ps.executeUpdate();
            if(exe > 0 ){
                JOptionPane.showMessageDialog(null, "Pedido registrado");
                setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                limpiarCajas();
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar los datos en la BD");
            }
        }catch(Exception ex){
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            jTextField1.setText("");
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            ex.printStackTrace();
        }
        JasperReport reporte = null;
        String path = "pnotes/Pedido_v3.jasper";
        try {
            /*Variable que sirve para recivir la consulta MySQL*/
            ResultSet id = null;
            String consulta = "select MAX(id_Cliente) from cliente;";
            Statement s = con.createStatement();
            id = s.executeQuery(consulta);
            /*Mapeo de los parametros, para poder hacer un mapeo de las variables para el filtro del reporte*/
            Map parametro = new HashMap();
            /*Se ingresa el parametro diseñado*/
            id.next();
            System.out.println("id de consulta"+id+"\nExecute querty"+id.toString()+"\nnext "+id.getString(1));
            String id_ = id.getString("MAX(id_Cliente)");
            parametro.put("id_Cliente",Integer.parseInt(id_));
            /*Se manda a llamar el reporte */
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            /*Esta variable sirve para el llenado del reporte
             Donde (Reporte, null, la conexcio con BD)
            */
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro,con);
            /*Se crea la vista del reporte*/ 
            JasperViewer view = new JasperViewer(jprint,false);
            /*Funcion para que se cierre el reporte*/
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);  
        } catch (SQLException ex) {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            Logger.getLogger(Banquetes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            Logger.getLogger(Banquetes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        System.out.println("Cliente: "+ np.getCliente()+"\nDomicilio: "+ np.getDomicilio()+"\nNumero Casa: "+np.getNumCasa()+"\nNumero Oficina: "+np.getNumOficina());
        System.out.println("Fecha evento: " + np.getFecha_evento() +"\nNumero evento : "+ np.getNumEvento()+"\nFecha pedido: "+ ld.getYear() + "-"+ld.getMonthValue()+"-"+ld.getDayOfYear());
        System.out.println(jDateChooser1.getDate().toString()+"\n"+jDateChooser1.toString()+"\n"+jDateChooser1.getDateFormatString());
        System.out.println(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*Opcion para cancelar el pedido*/
        int choice = JOptionPane.showConfirmDialog(null, "¿Estás seguro de cancelar el pedido?","Cancelar pedido",JOptionPane.YES_NO_OPTION);
        if(choice == 0){
            Menu menu = new Menu();
            menu.setVisible(true);
            setVisible(false);
        }else{
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jLabel12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_jLabel12MouseDragged

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jLabel12MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    private static final String url = "jdbc:mysql://localhost:3306/notes?autoReconnect=true&useSSL=false";
    private static final String user = "root";
    private static String password = "1234";
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*Se establece coneccion con la base de datos*/
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banquetes().setVisible(true);
            }
        });
    }
    private void limpiarCajas(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField8.setText("");
        jTextArea1.setText("");
        jDateChooser1.setToolTipText("AAAA-MM-DD");
    }
    private static Connection getConection(){
        Connection con = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, user, password);
            //JOptionPane.showMessageDialog(null,"Conexion exitosa");
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return con;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
